"""
Contract B - Vulnerability Manifest

This module defines the schema, validation logic, and constants for Contract B,
which is produced by the FSA (analyzer.py) and consumed by the OSE Server (main.py).

Contract B contains the confirmed vulnerability findings generated by the
Financial Semantic Analyzer, including vulnerability type, severity, location,
code snippet, description, and fix principle.

Validation rules implemented (see Data Contract Specification):
    B-001: file_path cross-reference against Contract A is NOT performed
           here -- it requires Contract A's file list and is handled by
           the orchestrator, which has both contracts in scope.
    B-002: line_end must be >= line_start.
    B-003: code_snippet must not contain absolute paths or user-specific
           information.
    B-004: vulnerability_class must be one of VULNERABILITY_CLASSES.
    B-005: confidence must be between 0.0 and 1.0 inclusive.
    B-006: findings array must not exceed MAX_FINDINGS items.
    B-007: each finding `id` must be unique within the findings array.
    B-008: analysis_metadata.target_tracks must be a non-empty array.

Thread-safety note: this module holds no mutable module-level state.
All "constants" below are read-only lookup tables (never mutated after
import), and every validation/generation function operates purely on
its arguments and local variables, so the module is safe for concurrent
use by multiple threads.
"""

import logging
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


class ValidationError(Exception):
    """Raised when a payload fails Contract B validation.

    All validation problems found in a single pass are collected and
    exposed both as ``self.errors`` (a list of individual messages) and
    folded into the exception's string representation.
    """

    def __init__(self, errors: Any) -> None:
        if isinstance(errors, str):
            errors = [errors]
        self.errors: List[str] = list(errors)
        message = "Contract B validation failed:\n" + "\n".join(
            f"- {e}" for e in self.errors
        )
        super().__init__(message)


# --------------------------------------------------------------------------
# Constants
# --------------------------------------------------------------------------

VERSION = "1.0.0"
MAX_FINDINGS = 100
DEFAULT_CONFIDENCE = 0.5

MAX_CODE_SNIPPET_LENGTH = 4096
MAX_DESCRIPTION_LENGTH = 1000
MAX_FIX_PRINCIPLE_LENGTH = 500

VULNERABILITY_CLASSES = [
    "REENTRANCY",
    "BROKEN_AUTH",
    "SLIPPAGE_OMISSION",
    "RACE_CONDITION",
    "DOUBLE_SPEND",
    "UNCHECKED_EXTERNAL_CALL",
    "MISSING_VALIDATION",
    "TX_ORIGIN_ABUSE",
    "BROKEN_ACCESS_CONTROL",
    "PRIVILEGE_ESCALATION",
    "ARITHMETIC_OVERFLOW",
    "LOGIC_FLAW",
    "INVALID_STATE_TRANSITION",
    "FINANCIAL_ACTION_ORDERING",
    "SETTLEMENT_BYPASS",
]

SEVERITY_LEVELS = ["CRITICAL", "HIGH", "MEDIUM", "LOW"]
FALSE_POSITIVE_RISK_LEVELS = ["LOW", "MEDIUM", "HIGH"]
TRACKS = ["web2", "web3", "quant"]
PREFERRED_MODELS = ["claude-3.5-sonnet", "gpt-4"]

# Short, stable abbreviations used by generate_finding_id() so that IDs
# stay readable (e.g. "BAUTH" for BROKEN_AUTH) instead of being truncated
# arbitrarily.
_VULN_CLASS_ABBREVIATIONS = {
    "REENTRANCY": "REENT",
    "BROKEN_AUTH": "BAUTH",
    "SLIPPAGE_OMISSION": "SLIP",
    "RACE_CONDITION": "RACE",
    "DOUBLE_SPEND": "DSPEND",
    "UNCHECKED_EXTERNAL_CALL": "UNCHK",
    "MISSING_VALIDATION": "MISVAL",
    "TX_ORIGIN_ABUSE": "TXORIG",
    "BROKEN_ACCESS_CONTROL": "BACCESS",
    "PRIVILEGE_ESCALATION": "PRIVESC",
    "ARITHMETIC_OVERFLOW": "ARITH",
    "LOGIC_FLAW": "LOGIC",
}

CONTRACT_VERSION_PATTERN = re.compile(r"^1\.[0-9]+\.[0-9]+$")
PROJECT_HASH_PATTERN = re.compile(r"^[a-f0-9]{64}$")
ISO8601_PATTERN = re.compile(
    r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$"
)
# Finding IDs combine a class abbreviation with a zero-padded sequence
# number, e.g. "FSA-BAUTH-001" (see generate_finding_id()).
FINDING_ID_PATTERN = re.compile(r"^FSA-[A-Z0-9]{3,10}-\d{3,}$")

# Substrings/patterns that indicate a code_snippet leaked an absolute,
# user-specific filesystem path (rule B-003).
_ABSOLUTE_PATH_INDICATORS = ("/Users/", "/home/", "/root/")
_WINDOWS_DRIVE_PATTERN = re.compile(r"[a-zA-Z]:\\")

REQUIRED_FINDING_FIELDS = (
    "id",
    "file_path",
    "line_start",
    "line_end",
    "vulnerability_class",
    "severity",
    "code_snippet",
    "description",
    "fix_principle",
)

REQUIRED_METADATA_FIELDS = (
    "scanner_version",
    "files_analyzed",
    "analysis_duration_seconds",
    "target_tracks",
)

logger = logging.getLogger("ose.contract_b")


# --------------------------------------------------------------------------
# Dataclasses (optional typed views over the raw dict payload)
# --------------------------------------------------------------------------

@dataclass
class Finding:
    """A single confirmed vulnerability finding."""

    id: str
    file_path: str
    line_start: int
    line_end: int
    vulnerability_class: str
    severity: str
    code_snippet: str
    description: str
    fix_principle: str
    confidence: float = DEFAULT_CONFIDENCE
    false_positive_risk: Optional[str] = None
    related_finding_ids: Optional[List[str]] = None


@dataclass
class ContractB:
    """The full Contract B payload: the Vulnerability Manifest."""

    contract_version: str
    project_hash: str
    generated_at: str
    analysis_metadata: Dict[str, Any]
    findings: List[Finding] = field(default_factory=list)
    request_metadata: Optional[Dict[str, Any]] = None


# --------------------------------------------------------------------------
# Internal helpers
# --------------------------------------------------------------------------

def _contains_absolute_path(snippet: str) -> bool:
    """Return True if `snippet` appears to leak an absolute filesystem path."""
    if any(indicator in snippet for indicator in _ABSOLUTE_PATH_INDICATORS):
        return True
    return _WINDOWS_DRIVE_PATTERN.search(snippet) is not None


def _validate_finding(
    finding: Any, index: int, seen_ids: set, errors: List[str]
) -> Optional[Dict[str, Any]]:
    """Validate a single findings[index] entry, appending problems to `errors`.

    Returns a cleaned copy of the finding (with a defaulted `confidence`
    where applicable), or None if the entry was not a dict at all.
    """
    if not isinstance(finding, dict):
        errors.append(
            f"findings[{index}]: expected an object, got {type(finding).__name__}"
        )
        return None

    cleaned = dict(finding)

    for required_field in REQUIRED_FINDING_FIELDS:
        if required_field not in finding:
            errors.append(
                f"findings[{index}].{required_field}: required field is missing"
            )

    # id (B-007 uniqueness, format)
    finding_id = finding.get("id")
    if not isinstance(finding_id, str) or not FINDING_ID_PATTERN.match(finding_id):
        errors.append(
            f"findings[{index}].id: must match pattern "
            f"'{FINDING_ID_PATTERN.pattern}' (got {finding_id!r})"
        )
    elif finding_id in seen_ids:
        errors.append(
            f"findings[{index}].id: duplicate id '{finding_id}' "
            "(rule B-007: ids must be unique within findings)"
        )
    else:
        seen_ids.add(finding_id)

    # file_path
    file_path = finding.get("file_path")
    if not isinstance(file_path, str) or not file_path:
        errors.append(
            f"findings[{index}].file_path: required non-empty string field "
            "is missing or invalid"
        )

    # line_start / line_end (B-002)
    line_start = finding.get("line_start")
    line_end = finding.get("line_end")
    valid_line_start = isinstance(line_start, int) and not isinstance(
        line_start, bool) and line_start >= 1
    valid_line_end = isinstance(
        line_end, int) and not isinstance(line_end, bool)
    if not valid_line_start:
        errors.append(
            f"findings[{index}].line_start: must be an integer >= 1 "
            f"(got {line_start!r})"
        )
    if not valid_line_end:
        errors.append(
            f"findings[{index}].line_end: must be an integer (got {line_end!r})"
        )
    if valid_line_start and valid_line_end and line_end < line_start:
        errors.append(
            f"findings[{index}].line_end: must be >= line_start "
            f"(got line_end={line_end}, line_start={line_start}) (rule B-002)"
        )

    # vulnerability_class (B-004)
    vuln_class = finding.get("vulnerability_class")
    if vuln_class not in VULNERABILITY_CLASSES:
        errors.append(
            f"findings[{index}].vulnerability_class: must be one of "
            f"{VULNERABILITY_CLASSES} (got {vuln_class!r}) (rule B-004)"
        )

    # severity
    severity = finding.get("severity")
    if severity not in SEVERITY_LEVELS:
        errors.append(
            f"findings[{index}].severity: must be one of {SEVERITY_LEVELS} "
            f"(got {severity!r})"
        )

    # code_snippet (B-003, length)
    code_snippet = finding.get("code_snippet")
    if not isinstance(code_snippet, str):
        errors.append(
            f"findings[{index}].code_snippet: required string field is "
            "missing or invalid"
        )
    else:
        if len(code_snippet) > MAX_CODE_SNIPPET_LENGTH:
            errors.append(
                f"findings[{index}].code_snippet: exceeds maximum length of "
                f"{MAX_CODE_SNIPPET_LENGTH} characters (got {len(code_snippet)})"
            )
        if _contains_absolute_path(code_snippet):
            errors.append(
                f"findings[{index}].code_snippet: must not contain absolute "
                "paths or user-specific information (rule B-003)"
            )

    # description
    description = finding.get("description")
    if not isinstance(description, str) or not description:
        errors.append(
            f"findings[{index}].description: required non-empty string "
            "field is missing or invalid"
        )
    elif len(description) > MAX_DESCRIPTION_LENGTH:
        errors.append(
            f"findings[{index}].description: exceeds maximum length of "
            f"{MAX_DESCRIPTION_LENGTH} characters (got {len(description)})"
        )

    # fix_principle
    fix_principle = finding.get("fix_principle")
    if not isinstance(fix_principle, str) or not fix_principle:
        errors.append(
            f"findings[{index}].fix_principle: required non-empty string "
            "field is missing or invalid"
        )
    elif len(fix_principle) > MAX_FIX_PRINCIPLE_LENGTH:
        errors.append(
            f"findings[{index}].fix_principle: exceeds maximum length of "
            f"{MAX_FIX_PRINCIPLE_LENGTH} characters (got {len(fix_principle)})"
        )

    # confidence (B-005, with default)
    if "confidence" not in finding or finding.get("confidence") is None:
        logger.warning(
            "findings[%d]: confidence is missing; defaulting to %.1f",
            index,
            DEFAULT_CONFIDENCE,
        )
        cleaned["confidence"] = DEFAULT_CONFIDENCE
    else:
        confidence = finding.get("confidence")
        is_number = isinstance(confidence, (int, float)
                               ) and not isinstance(confidence, bool)
        if not is_number or not (0.0 <= float(confidence) <= 1.0):
            errors.append(
                f"findings[{index}].confidence: must be between 0.0 and 1.0 "
                f"(got {confidence!r}) (rule B-005)"
            )
        else:
            cleaned["confidence"] = float(confidence)

    # optional: false_positive_risk
    if "false_positive_risk" in finding and finding["false_positive_risk"] is not None:
        if finding["false_positive_risk"] not in FALSE_POSITIVE_RISK_LEVELS:
            errors.append(
                f"findings[{index}].false_positive_risk: must be one of "
                f"{FALSE_POSITIVE_RISK_LEVELS} (got {finding['false_positive_risk']!r})"
            )

    # optional: related_finding_ids
    if "related_finding_ids" in finding and finding["related_finding_ids"] is not None:
        related = finding["related_finding_ids"]
        if not isinstance(related, list) or not all(isinstance(r, str) for r in related):
            errors.append(
                f"findings[{index}].related_finding_ids: must be an array "
                "of strings if present"
            )

    return cleaned


def _validate_analysis_metadata(metadata: Any, errors: List[str]) -> Optional[Dict[str, Any]]:
    """Validate the `analysis_metadata` object, appending problems to `errors`."""
    if not isinstance(metadata, dict):
        errors.append("analysis_metadata: required field must be an object")
        return None

    cleaned = dict(metadata)

    for required_field in REQUIRED_METADATA_FIELDS:
        if required_field not in metadata:
            errors.append(
                f"analysis_metadata.{required_field}: required field is missing"
            )

    scanner_version = metadata.get("scanner_version")
    if "scanner_version" in metadata and (
        not isinstance(scanner_version, str) or not scanner_version
    ):
        errors.append(
            "analysis_metadata.scanner_version: must be a non-empty string"
        )

    files_analyzed = metadata.get("files_analyzed")
    if "files_analyzed" in metadata and (
        not isinstance(files_analyzed, int)
        or isinstance(files_analyzed, bool)
        or files_analyzed < 0
    ):
        errors.append(
            "analysis_metadata.files_analyzed: must be a non-negative integer "
            f"(got {files_analyzed!r})"
        )

    duration = metadata.get("analysis_duration_seconds")
    if "analysis_duration_seconds" in metadata and (
        not isinstance(duration, (int, float))
        or isinstance(duration, bool)
        or duration < 0
    ):
        errors.append(
            "analysis_metadata.analysis_duration_seconds: must be a "
            f"non-negative number (got {duration!r})"
        )

    # target_tracks (B-008)
    target_tracks = metadata.get("target_tracks")
    if "target_tracks" in metadata:
        if not isinstance(target_tracks, list) or len(target_tracks) < 1:
            errors.append(
                "analysis_metadata.target_tracks: must be a non-empty array "
                "(rule B-008)"
            )
        else:
            invalid_tracks = [t for t in target_tracks if t not in TRACKS]
            if invalid_tracks:
                errors.append(
                    f"analysis_metadata.target_tracks: contains unsupported "
                    f"track(s) {invalid_tracks}; must be a subset of {TRACKS}"
                )

    return cleaned


def _validate_request_metadata(metadata: Any, errors: List[str]) -> Optional[Dict[str, Any]]:
    """Validate the optional `request_metadata` object, appending problems to `errors`."""
    if metadata is None:
        return None
    if not isinstance(metadata, dict):
        errors.append("request_metadata: must be an object if present")
        return None

    cleaned = dict(metadata)

    if "client_version" in metadata and not isinstance(metadata["client_version"], str):
        errors.append(
            "request_metadata.client_version: must be a string if present")

    if "user_id" in metadata and not isinstance(metadata["user_id"], str):
        errors.append("request_metadata.user_id: must be a string if present")

    if "preferred_model" in metadata:
        if metadata["preferred_model"] not in PREFERRED_MODELS:
            errors.append(
                "request_metadata.preferred_model: must be one of "
                f"{PREFERRED_MODELS} (got {metadata['preferred_model']!r})"
            )

    return cleaned


# --------------------------------------------------------------------------
# Public API
# --------------------------------------------------------------------------

def validate_contract_b(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Validate that `data` conforms to the Contract B schema (Vulnerability Manifest).

    All applicable validation rules (B-002 through B-008; B-001 is left to
    the orchestrator, which has Contract A available for cross-reference)
    are checked in a single pass; every problem found is collected rather
    than raising on the first failure.

    Args:
        data: The parsed payload (e.g. from analyzer.py's JSON output).

    Returns:
        A cleaned/normalized copy of `data`, with missing `confidence`
        values defaulted to DEFAULT_CONFIDENCE.

    Raises:
        ValidationError: If `data` does not conform to the Contract B
            schema. The exception's `errors` attribute holds the full
            list of individual problems found.
    """
    errors: List[str] = []

    if not isinstance(data, dict):
        raise ValidationError(
            f"Contract B payload must be an object, got {type(data).__name__}"
        )

    # contract_version
    contract_version = data.get("contract_version")
    if not isinstance(contract_version, str) or not CONTRACT_VERSION_PATTERN.match(
        contract_version
    ):
        errors.append(
            "contract_version: must match pattern "
            f"'{CONTRACT_VERSION_PATTERN.pattern}' (got {contract_version!r})"
        )

    # project_hash
    project_hash = data.get("project_hash")
    if not isinstance(project_hash, str) or not PROJECT_HASH_PATTERN.match(project_hash):
        errors.append(
            "project_hash: must be a 64-character lowercase SHA-256 hex "
            f"digest (got {project_hash!r})"
        )

    # generated_at
    generated_at = data.get("generated_at")
    if not isinstance(generated_at, str) or not ISO8601_PATTERN.match(generated_at):
        errors.append(
            "generated_at: must be an ISO 8601 UTC timestamp "
            f"(got {generated_at!r})"
        )

    # analysis_metadata (B-008)
    cleaned_metadata = _validate_analysis_metadata(
        data.get("analysis_metadata"), errors)

    # findings (B-002, B-003, B-004, B-005, B-006, B-007)
    findings = data.get("findings")
    if not isinstance(findings, list):
        errors.append(
            "findings: required field must be a list of finding objects")
        findings = []

    if len(findings) > MAX_FINDINGS:
        errors.append(
            f"findings array exceeds maximum of {MAX_FINDINGS} items "
            f"(got {len(findings)}) (rule B-006)"
        )

    seen_ids: set = set()
    cleaned_findings: List[Dict[str, Any]] = []
    for i, finding in enumerate(findings):
        cleaned_finding = _validate_finding(finding, i, seen_ids, errors)
        if cleaned_finding is not None:
            cleaned_findings.append(cleaned_finding)

    # request_metadata (optional)
    cleaned_request_metadata = _validate_request_metadata(
        data.get("request_metadata"), errors
    )

    if errors:
        raise ValidationError(errors)

    cleaned_data = dict(data)
    cleaned_data["contract_version"] = contract_version
    cleaned_data["project_hash"] = project_hash
    cleaned_data["generated_at"] = generated_at
    cleaned_data["analysis_metadata"] = cleaned_metadata
    cleaned_data["findings"] = cleaned_findings
    if "request_metadata" in data:
        cleaned_data["request_metadata"] = cleaned_request_metadata
    return cleaned_data


def is_valid_contract_b(data: Dict[str, Any]) -> bool:
    """Return True if `data` is a valid Contract B payload, False otherwise."""
    try:
        validate_contract_b(data)
        return True
    except ValidationError:
        return False


def generate_finding_id(vulnerability_class: str, index: int) -> str:
    """
    Generate a finding ID in the format "FSA-XXXXXX-001".

    The class segment is a short, stable abbreviation of
    `vulnerability_class` (see `_VULN_CLASS_ABBREVIATIONS`); unknown
    classes fall back to their first 6 alphanumeric characters,
    uppercased. The sequence segment is `index` zero-padded to at
    least 3 digits.

    Args:
        vulnerability_class: One of the values in VULNERABILITY_CLASSES
            (e.g. "BROKEN_AUTH"). Unrecognized values are still accepted
            and abbreviated on a best-effort basis.
        index: A 1-based sequence number for this finding within the
            current run (e.g. 1, 2, 3...).

    Returns:
        A string such as "FSA-BAUTH-001".
    """
    if vulnerability_class in _VULN_CLASS_ABBREVIATIONS:
        abbreviation = _VULN_CLASS_ABBREVIATIONS[vulnerability_class]
    else:
        alnum_only = re.sub(r"[^A-Za-z0-9]", "", vulnerability_class or "")
        abbreviation = (alnum_only[:6] or "UNKNOWN").upper()

    sequence = max(index, 0)
    return f"FSA-{abbreviation}-{sequence:03d}"


def get_contract_b_schema() -> Dict[str, Any]:
    """Return the JSON Schema (draft-07) representation of Contract B."""
    return {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "ContractB_VulnerabilityManifest",
        "description": (
            "Vulnerability Manifest produced by the FSA (analyzer.py) and "
            "consumed by the OSE Server (main.py)."
        ),
        "type": "object",
        "required": [
            "contract_version",
            "project_hash",
            "generated_at",
            "analysis_metadata",
            "findings",
        ],
        "properties": {
            "contract_version": {
                "type": "string",
                "pattern": CONTRACT_VERSION_PATTERN.pattern,
            },
            "project_hash": {
                "type": "string",
                "pattern": PROJECT_HASH_PATTERN.pattern,
            },
            "generated_at": {
                "type": "string",
                "pattern": ISO8601_PATTERN.pattern,
                "description": "ISO 8601 UTC timestamp.",
            },
            "analysis_metadata": {
                "type": "object",
                "required": list(REQUIRED_METADATA_FIELDS),
                "properties": {
                    "scanner_version": {"type": "string"},
                    "files_analyzed": {"type": "integer", "minimum": 0},
                    "analysis_duration_seconds": {"type": "number", "minimum": 0},
                    "target_tracks": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"type": "string", "enum": TRACKS},
                        "description": "Rule B-008: must be non-empty.",
                    },
                },
            },
            "findings": {
                "type": "array",
                "maxItems": MAX_FINDINGS,
                "items": {
                    "type": "object",
                    "required": list(REQUIRED_FINDING_FIELDS),
                    "properties": {
                        "id": {
                            "type": "string",
                            "pattern": FINDING_ID_PATTERN.pattern,
                        },
                        "file_path": {"type": "string"},
                        "line_start": {"type": "integer", "minimum": 1},
                        "line_end": {
                            "type": "integer",
                            "description": "Must be >= line_start (rule B-002).",
                        },
                        "vulnerability_class": {
                            "type": "string",
                            "enum": VULNERABILITY_CLASSES,
                        },
                        "severity": {"type": "string", "enum": SEVERITY_LEVELS},
                        "code_snippet": {
                            "type": "string",
                            "maxLength": MAX_CODE_SNIPPET_LENGTH,
                            "description": (
                                "Must not contain absolute paths or "
                                "user-specific information (rule B-003)."
                            ),
                        },
                        "description": {
                            "type": "string",
                            "maxLength": MAX_DESCRIPTION_LENGTH,
                        },
                        "fix_principle": {
                            "type": "string",
                            "maxLength": MAX_FIX_PRINCIPLE_LENGTH,
                        },
                        "confidence": {
                            "type": "number",
                            "minimum": 0.0,
                            "maximum": 1.0,
                            "default": DEFAULT_CONFIDENCE,
                        },
                        "false_positive_risk": {
                            "type": "string",
                            "enum": FALSE_POSITIVE_RISK_LEVELS,
                        },
                        "related_finding_ids": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                    },
                },
            },
            "request_metadata": {
                "type": "object",
                "properties": {
                    "client_version": {"type": "string"},
                    "user_id": {"type": "string"},
                    "preferred_model": {
                        "type": "string",
                        "enum": PREFERRED_MODELS,
                    },
                },
            },
        },
    }
